config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parkings
  root "parkings#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord

  belongs_to :user, :optional => true

  #valid
  validates_presence_of :parking_type, :start_at
  validates_inclusion_of :parking_type, :in => ["guest", "short-term", "long-term"]
  validate :validate_end_at_with_amount

  def validate_end_at_with_amount
    if ( end_at.present? && amount.blank? )
      errors.add(:amount, "有結束時間就必須有金額")
    end

    if ( end_at.blank? && amount.present? )
      errors.add(:end_at, "有金額就必須有結束時間")
    end
  end

  
  def duration
    ( end_at - start_at ) / 60
  end

  def calculate_amount
    if self.amount.blank? && self.start_at.present? && self.end_at.present?
      if self.user.blank?
        self.amount = calculate_guest_term_amount  # 一般費率
      elsif self.parking_type == "long-term"
          self.amount = calculate_long_term_amount # 長期費率
      elsif self.parking_type == "short-term"
        self.amount = calculate_short_term_amount  # 短期費率
      end
    end
  end

  def calculate_guest_term_amount
    if duration <= 60
      self.amount = 200
    else
      self.amount = 200 + ((duration - 60).to_f / 30).ceil * 100
    end
  end

  def calculate_short_term_amount
    if duration <= 60
      self.amount = 200
    else
      self.amount = 200 + ((duration - 60).to_f / 30).ceil * 50
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :parkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :find_parking, only: %i[show update]
  
  def new
    @parking = Parking.new
  end
  
  def create
    @parking = Parking.new(start_at: Time.now )

    if current_user
      @parking.parking_type = params[:parking][:parking_type]
      @parking.user = current_user
    else
      @parking.parking_type = "guest"
    end
    
    @parking.save!
    redirect_to parking_path(@parking)
  end

  def show
  end
  
  def update
    @parking.end_at = Time.now
    @parking.calculate_amount 
    @parking.save!
    redirect_to parking_path(@parking)
  end

  private
  
  def find_parking
    @parking = Parking.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>

    <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
      <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/parkings/new.html.erb
<h1>停車費用計算</h1>

<%= form_for @parking do |f| %>

  <% if current_user %>

    <label>
      <%= f.radio_button :parking_type, "short-term" %> 短期費率
    </label>

    <label>
      <%= f.radio_button :parking_type, "long-term" %> 長期費率
    </label>

  <% else %>
    一般費率
  <% end %>

  <p><%= f.submit "開始計費" %></p>

<% end %>

app/views/parkings/show.html.erb
<h1>停車費用計算</h1>

<% if @parking.amount.present? %>

  <p>從 <%= @parking.start_at %> 至 <%= @parking.end_at %><p>
  <p>共 <%= @parking.duration %> 分鐘</p>
  <p>總計 <%= number_to_currency(@parking.amount.to_f / 100, :unit => "¥") %> 元</p>

  <p><%= link_to "繼續停車", new_parking_path %></p>

<% else  %>

  <%= form_for @parking do |f| %>
  
    <p>計費方式 <%= @parking.parking_type %></p>
    <p><%= f.submit "結束計費" %></p>

  <% end %>

<% end %>